---
- hosts: ansible-server
  become: true

  tasks:
  - name: create docker image using war file
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/k8s

  - name: create tag to image
    command: docker tag simple-devops-image nagendra464/simple-devops-image

  - name: push image on to dockerhub
    command: docker push nagendra464/simple-devops-image

  - name: remove docker images form ansible server
    command: docker rmi simple-devops-image:latest nagendra464/simple-devops-image
    ignore_errors: yes
	
	
	
	apiVersion: v1
kind: Service
metadata:
  name: valaxy-service
  labels:
    app: valaxy-devops-project
spec:
  selector:
    app: valaxy-devops-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200


apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: valaxy-deployment
spec:
  selector:
    matchLabels:
      app: valaxy-devops-project
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: valaxy-devops-project
    spec:
      containers:
      - name: valaxy-devops-project
        image: nagendra464/simple-devops-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080